### ISSUE TITLE
Cannot upload po file: Unable to open the file

### ISSUE THREAD

**Issue by super7ramp** [dahool/vertaal#16]
On https://vertaal-sgtdev.rhcloud.com, I can't upload po files anymore.

The first time the problem occured was a few days ago with [vpn.fr.po](https://vertaal-sgtdev.rhcloud.com/files/factory-yast-fr-vpn-fr-po/detail/).

When I clicked on the upload button an error showed up:
> Please, fix the following errors and upload the file again:
> Unable to open the file vpn.fr.po

Then the French team's coordinator has manually uploaded the file on the svn server ([rev 92620](https://svn.opensuse.org/viewvc/opensuse-i18n/trunk/yast/fr/po/vpn.fr.po?view=markup&revision=92620)) but it looks like Vertaal haven't synchronised yet.

Same thing happened with [zypper.fr.po](https://vertaal-sgtdev.rhcloud.com/files/factory-lcn-fr-zypper-fr-po/detail/). It looks like it's not an isolated problem (our team's coordinator encounters the same issue). I don't know if other languages are concerned though.

**Comment by dahool** [comment]
Thanks, I'll take a look.

**Comment by super7ramp** [comment]
It seems that Vertaal has just synced. I have successfully uploaded a po (zypper.fr.po) so it looks like the situation is back to normal… Thank you :-)
