### ISSUE TITLE
Vertaal instance down

### ISSUE THREAD

**Issue by super7ramp** [dahool/vertaal#17]
http://vertaal-sgtdev.rhcloud.com/ is down for some time now, what's wrong?

**Comment by dahool** [comment]
Hello, OS team is migrating everything to weblate, so there is no sense in keep maintaining vertaal. Also, there hasn't been any update on the svn for leap, so I decided to use the RH slot in something more useful to me.

**Comment by super7ramp** [comment]
Thanks for your fast reply.

> Hello, OS team is migrating everything to weblate, so there is no sense in keep maintaining vertaal. 

Yes I know, but it's not done yet.

> Also, there hasn't been any update on the svn for leap, so I decided to use the RH slot in something more useful to me.

Leap may have no update but Tumbleweed/Factory has. Anyway, thanks for what you've done so far ;)
